[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckInterval = 10
healthcheckTimeout = 5
restartPolicyMaxRetries = 5
